### ISSUE TITLE
Add an option to use the projects .luacheckrc

### ISSUE THREAD

**Issue by theFox6** [Roang-zero1/factorio-mod-luacheck#2]
I wish to suggest a new option.
If it's set to true luacheck should use the .luacheckrc that can be found within the folder to be checked.
Right now I'm using this workaround:
```yaml
name: luacheck

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: run luacheck
        uses: Roang-zero1/factorio-mod-luacheck@master
        with:
          LUACHECKRC_URL: https://raw.githubusercontent.com/${{github.repository}}/${{github.sha}}/.luacheckrc
```
